   name: Deploy Hugo site from Notion

   on:
     push:
       branches: 
          - main
     workflow_dispatch:

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Setup Python
           uses: actions/setup-python@v4
           with:
             python-version: '3.12'

         - name: Install Python dependencies
           run: |
             pip install -r requirements.txt

         - name: Run Notion to Markdown
           run: |
             python notion_to_markdown.py

         - name: Setup Hugo
           uses: peaceiris/actions-hugo@v2
           with:
             hugo-version: 'latest'
             extended: true

         - name: Build Hugo Site
           run: hugo --minify

         - name: Deploy to Github Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${ secrets.GITHUB_TOKEN }}
             publish_dir: ./public

     
